/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Color;

/**
 *
 * @author HP
 */
public class acceso extends javax.swing.JFrame {

	/**
	 * Creates new form acceso
	 */
	public acceso() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoTaoAcceso = new javax.swing.JLabel();
        accesoLabel = new javax.swing.JLabel();
        usuarioLabel = new javax.swing.JLabel();
        campoNumCedula = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        pinCuentaLabel = new javax.swing.JLabel();
        campoPinCuenta = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        botonEntrarAcceso = new javax.swing.JButton();
        botonNuevaCuentaAcceso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 385));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_interfaz_recortado.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");

        logoTaoAcceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoTaoBanking.png"))); // NOI18N

        accesoLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        accesoLabel.setForeground(new java.awt.Color(0, 0, 0));
        accesoLabel.setText("ACCESO");

        usuarioLabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        usuarioLabel.setForeground(new java.awt.Color(0, 0, 0));
        usuarioLabel.setText("USUARIO");

        campoNumCedula.setBackground(new java.awt.Color(255, 255, 255));
        campoNumCedula.setForeground(new java.awt.Color(204, 204, 204));
        campoNumCedula.setText("Ingrese su número de cédula");
        campoNumCedula.setBorder(null);
        campoNumCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNumCedulaMouseClicked(evt);
            }
        });
        campoNumCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNumCedulaKeyTyped(evt);
            }
        });

        pinCuentaLabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        pinCuentaLabel.setForeground(new java.awt.Color(0, 0, 0));
        pinCuentaLabel.setText("PIN DE CUENTA");

        campoPinCuenta.setBackground(new java.awt.Color(255, 255, 255));
        campoPinCuenta.setForeground(new java.awt.Color(204, 204, 204));
        campoPinCuenta.setText("Ingrese su pin de cuenta");
        campoPinCuenta.setBorder(null);
        campoPinCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoPinCuentaMouseClicked(evt);
            }
        });
        campoPinCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPinCuentaActionPerformed(evt);
            }
        });
        campoPinCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoPinCuentaKeyTyped(evt);
            }
        });

        botonEntrarAcceso.setText("ENTRAR");
        botonEntrarAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntrarAccesoActionPerformed(evt);
            }
        });

        botonNuevaCuentaAcceso.setText("NUEVA CUENTA");
        botonNuevaCuentaAcceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaCuentaAccesoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(accesoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(101, 101, 101))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(usuarioLabel)
                                .addComponent(campoNumCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pinCuentaLabel)
                                .addComponent(campoPinCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(botonEntrarAcceso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botonNuevaCuentaAcceso))
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(23, 23, 23)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(logoTaoAcceso, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoTaoAcceso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accesoLabel)
                .addGap(24, 24, 24)
                .addComponent(usuarioLabel)
                .addGap(2, 2, 2)
                .addComponent(campoNumCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pinCuentaLabel)
                .addGap(2, 2, 2)
                .addComponent(campoPinCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEntrarAcceso)
                    .addComponent(botonNuevaCuentaAcceso))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoPinCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPinCuentaActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_campoPinCuentaActionPerformed

    private void campoNumCedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNumCedulaMouseClicked
		if (campoNumCedula.getText().equals("Ingrese su número de cédula")) {
			campoNumCedula.setText("");
			campoNumCedula.setForeground(Color.black);
		}
    }//GEN-LAST:event_campoNumCedulaMouseClicked

    private void campoPinCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPinCuentaMouseClicked
		if (campoPinCuenta.getText().equals("Ingrese su pin de cuenta")) {
			campoPinCuenta.setText("");
			campoPinCuenta.setForeground(Color.black);
		}
    }//GEN-LAST:event_campoPinCuentaMouseClicked

    private void botonNuevaCuentaAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaCuentaAccesoActionPerformed
		// Al hacer click a este botón te lleva a la ventana de creación de cuenta nueva
		nuevaCuenta newFrame = new nuevaCuenta(); 
		newFrame.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_botonNuevaCuentaAccesoActionPerformed

    private void botonEntrarAccesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntrarAccesoActionPerformed
		// botón de la primera ventana, si se cumplen las condiciones te direcciona a la pantalla principal
		String nombre = campoNumCedula.getText();
		
		if (nombre.equals("Ingrese su número de cédula")  || nombre.equals("")){
			campoNumCedula.setText("Ingrese su número de cédula");
			campoNumCedula.setForeground(Color.red);
		}
		else{
			pantallaPrincipal newFrame = new pantallaPrincipal();
			newFrame.nombreUsuario.setText(nombre);
			newFrame.setVisible(true);
			this.dispose();
		}
		
		
    }//GEN-LAST:event_botonEntrarAccesoActionPerformed

    private void campoNumCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNumCedulaKeyTyped
		int key = evt.getKeyChar();

		boolean numeros = key >= 48 && key <= 57;

		if (!numeros) {
			evt.consume();
		}
    }//GEN-LAST:event_campoNumCedulaKeyTyped

    private void campoPinCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPinCuentaKeyTyped
		int key = evt.getKeyChar();

		boolean numeros = key >= 48 && key <= 57;

		if (!numeros) {
			evt.consume();
		}
    }//GEN-LAST:event_campoPinCuentaKeyTyped

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new acceso().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accesoLabel;
    private javax.swing.JButton botonEntrarAcceso;
    private javax.swing.JButton botonNuevaCuentaAcceso;
    private javax.swing.JTextField campoNumCedula;
    private javax.swing.JTextField campoPinCuenta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel logoTaoAcceso;
    private javax.swing.JLabel pinCuentaLabel;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
