/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.taobanking.ui.interfaz;

import java.awt.Color;

/**
 *
 * @author HP
 */
public class depositar extends javax.swing.JFrame {

	/**
	 * Creates new form depositar
	 */
	public depositar() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cedulaDestinatarioLabel = new javax.swing.JLabel();
        montoLabel = new javax.swing.JLabel();
        campoCuentaDestinatario = new javax.swing.JTextField();
        apellidoDestinatarioLabel = new javax.swing.JLabel();
        campoNombreDestinatario = new javax.swing.JTextField();
        campoApellidoDestinatario = new javax.swing.JTextField();
        nombreDestinatarioLabel = new javax.swing.JLabel();
        campoMonto = new javax.swing.JTextField();
        cuentaDestinatarioLabel = new javax.swing.JLabel();
        campoCedulaDestinatario = new javax.swing.JTextField();
        campoPinTransaccion = new javax.swing.JTextField();
        pinTransaccionLabel = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        logoTaoDepositar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        montoDepositoLabel = new javax.swing.JLabel();
        campoCuentaDepositar = new javax.swing.JTextField();
        campoMontoDeposito = new javax.swing.JTextField();
        cuentaDepositarLabel = new javax.swing.JLabel();
        campoPinTransaccion1 = new javax.swing.JTextField();
        pinTransaccionLabel1 = new javax.swing.JLabel();
        botonDepositar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3), "Transferencia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        cedulaDestinatarioLabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        cedulaDestinatarioLabel.setForeground(new java.awt.Color(0, 0, 0));
        cedulaDestinatarioLabel.setText("Nro. de Cédula del destinatario");

        montoLabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        montoLabel.setForeground(new java.awt.Color(0, 0, 0));
        montoLabel.setText("Monto a depositar");

        campoCuentaDestinatario.setBackground(new java.awt.Color(255, 255, 255));
        campoCuentaDestinatario.setForeground(new java.awt.Color(153, 153, 153));
        campoCuentaDestinatario.setText("Ingrese el número de cuenta");
        campoCuentaDestinatario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoCuentaDestinatarioMouseClicked(evt);
            }
        });
        campoCuentaDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCuentaDestinatarioActionPerformed(evt);
            }
        });

        apellidoDestinatarioLabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        apellidoDestinatarioLabel.setForeground(new java.awt.Color(0, 0, 0));
        apellidoDestinatarioLabel.setText("Apellido del destinatario");

        campoNombreDestinatario.setBackground(new java.awt.Color(255, 255, 255));
        campoNombreDestinatario.setForeground(new java.awt.Color(153, 153, 153));
        campoNombreDestinatario.setText("Ingrese el nombre");
        campoNombreDestinatario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNombreDestinatarioMouseClicked(evt);
            }
        });
        campoNombreDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreDestinatarioActionPerformed(evt);
            }
        });

        campoApellidoDestinatario.setBackground(new java.awt.Color(255, 255, 255));
        campoApellidoDestinatario.setForeground(new java.awt.Color(153, 153, 153));
        campoApellidoDestinatario.setText("Ingrese el apellido");
        campoApellidoDestinatario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoApellidoDestinatarioMouseClicked(evt);
            }
        });
        campoApellidoDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidoDestinatarioActionPerformed(evt);
            }
        });

        nombreDestinatarioLabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        nombreDestinatarioLabel.setForeground(new java.awt.Color(0, 0, 0));
        nombreDestinatarioLabel.setText("Nombre del destinatario");

        campoMonto.setBackground(new java.awt.Color(255, 255, 255));
        campoMonto.setForeground(new java.awt.Color(153, 153, 153));
        campoMonto.setText("Ingrese el monto a depositar");
        campoMonto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoMontoMouseClicked(evt);
            }
        });
        campoMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMontoActionPerformed(evt);
            }
        });

        cuentaDestinatarioLabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        cuentaDestinatarioLabel.setForeground(new java.awt.Color(0, 0, 0));
        cuentaDestinatarioLabel.setText("Nro. de Cuenta del destinatario");

        campoCedulaDestinatario.setBackground(new java.awt.Color(255, 255, 255));
        campoCedulaDestinatario.setForeground(new java.awt.Color(153, 153, 153));
        campoCedulaDestinatario.setText("Ingrese el número de cédula");
        campoCedulaDestinatario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoCedulaDestinatarioMouseClicked(evt);
            }
        });
        campoCedulaDestinatario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCedulaDestinatarioActionPerformed(evt);
            }
        });

        campoPinTransaccion.setBackground(new java.awt.Color(255, 255, 255));
        campoPinTransaccion.setForeground(new java.awt.Color(153, 153, 153));
        campoPinTransaccion.setText("Ingrese su pin de transacción");
        campoPinTransaccion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoPinTransaccionMouseClicked(evt);
            }
        });
        campoPinTransaccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPinTransaccionActionPerformed(evt);
            }
        });

        pinTransaccionLabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        pinTransaccionLabel.setForeground(new java.awt.Color(0, 0, 0));
        pinTransaccionLabel.setText("Pin de Transacción");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(campoApellidoDestinatario, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                    .addComponent(campoNombreDestinatario, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                    .addComponent(nombreDestinatarioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(apellidoDestinatarioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cuentaDestinatarioLabel)
                                            .addComponent(campoCuentaDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(montoLabel)
                                            .addComponent(campoPinTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(pinTransaccionLabel))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(cedulaDestinatarioLabel))
                        .addContainerGap(10, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(campoCedulaDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreDestinatarioLabel)
                    .addComponent(cuentaDestinatarioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoNombreDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoCuentaDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoDestinatarioLabel)
                    .addComponent(montoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoApellidoDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cedulaDestinatarioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoCedulaDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(pinTransaccionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPinTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(201, 42, 42));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoTaoDepositar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoTaoBankingRecortado.png"))); // NOI18N
        jPanel1.add(logoTaoDepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 130, 70));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 120, 70));

        jPanel4.setBackground(new java.awt.Color(242, 69, 69));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 170, 70));

        jPanel5.setBackground(new java.awt.Color(201, 42, 42));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 70));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3), "Depositar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        montoDepositoLabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        montoDepositoLabel.setForeground(new java.awt.Color(0, 0, 0));
        montoDepositoLabel.setText("Monto a depositar");

        campoCuentaDepositar.setBackground(new java.awt.Color(255, 255, 255));
        campoCuentaDepositar.setForeground(new java.awt.Color(153, 153, 153));
        campoCuentaDepositar.setText("Ingrese el número de cuenta");
        campoCuentaDepositar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoCuentaDepositarMouseClicked(evt);
            }
        });
        campoCuentaDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCuentaDepositarActionPerformed(evt);
            }
        });
        campoCuentaDepositar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCuentaDepositarKeyTyped(evt);
            }
        });

        campoMontoDeposito.setBackground(new java.awt.Color(255, 255, 255));
        campoMontoDeposito.setForeground(new java.awt.Color(153, 153, 153));
        campoMontoDeposito.setText("Ingrese el monto a depositar");
        campoMontoDeposito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoMontoDepositoMouseClicked(evt);
            }
        });
        campoMontoDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoMontoDepositoActionPerformed(evt);
            }
        });
        campoMontoDeposito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoMontoDepositoKeyTyped(evt);
            }
        });

        cuentaDepositarLabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        cuentaDepositarLabel.setForeground(new java.awt.Color(0, 0, 0));
        cuentaDepositarLabel.setText("Nro. de Cuenta a depositar");

        campoPinTransaccion1.setBackground(new java.awt.Color(255, 255, 255));
        campoPinTransaccion1.setForeground(new java.awt.Color(153, 153, 153));
        campoPinTransaccion1.setText("Ingrese su pin de transacción");
        campoPinTransaccion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoPinTransaccion1MouseClicked(evt);
            }
        });
        campoPinTransaccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPinTransaccion1ActionPerformed(evt);
            }
        });
        campoPinTransaccion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoPinTransaccion1KeyTyped(evt);
            }
        });

        pinTransaccionLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        pinTransaccionLabel1.setForeground(new java.awt.Color(0, 0, 0));
        pinTransaccionLabel1.setText("Pin de Transacción");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(montoDepositoLabel)
                        .addGap(141, 141, 141))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(campoMontoDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCuentaDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoPinTransaccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(pinTransaccionLabel1)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(cuentaDepositarLabel)
                        .addGap(119, 119, 119))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cuentaDepositarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoCuentaDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(montoDepositoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoMontoDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pinTransaccionLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoPinTransaccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 430, -1));

        botonDepositar.setText("DEPOSITAR");
        jPanel1.add(botonDepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        botonVolver.setText("VOLVER");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoCuentaDestinatarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoCuentaDestinatarioMouseClicked
        // Al hacer click en ingresar número de cuenta se borra el string por defecto
        if (campoCuentaDestinatario.getText().equals("Ingrese el número de cuenta")) {
            campoCuentaDestinatario.setText("");
            campoCuentaDestinatario.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoCuentaDestinatarioMouseClicked

    private void campoCuentaDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCuentaDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCuentaDestinatarioActionPerformed

    private void campoNombreDestinatarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNombreDestinatarioMouseClicked
        // Al hacer click en ingresar nombre se borra el string por defecto
        if (campoNombreDestinatario.getText().equals("Ingrese el nombre")) {
            campoNombreDestinatario.setText("");
            campoNombreDestinatario.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoNombreDestinatarioMouseClicked

    private void campoNombreDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoNombreDestinatarioActionPerformed

    private void campoApellidoDestinatarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoApellidoDestinatarioMouseClicked
        // Al hacer click en ingrese el apellido se borra el string por defecto
        if (campoApellidoDestinatario.getText().equals("Ingrese el apellido")) {
            campoApellidoDestinatario.setText("");
            campoApellidoDestinatario.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoApellidoDestinatarioMouseClicked

    private void campoApellidoDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoApellidoDestinatarioActionPerformed

    private void campoMontoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoMontoMouseClicked
        // Al hacer click en ingresar monto a depositar se borra el string por defecto
        if (campoMonto.getText().equals("Ingrese el monto a depositar")){
            campoMonto.setText("");
            campoMonto.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoMontoMouseClicked

    private void campoMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMontoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMontoActionPerformed

    private void campoCedulaDestinatarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoCedulaDestinatarioMouseClicked
        // Al hacer click en ingrese el número de cédula se borra el string por defecto
        if (campoCedulaDestinatario.getText().equals("Ingrese el número de cédula")) {
            campoCedulaDestinatario.setText("");
            campoCedulaDestinatario.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoCedulaDestinatarioMouseClicked

    private void campoCedulaDestinatarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCedulaDestinatarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCedulaDestinatarioActionPerformed

    private void campoPinTransaccionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPinTransaccionMouseClicked
        //Al hacer click en ingresar pin de transacción se borra el string por defecto
        if (campoPinTransaccion.getText().equals("Ingrese su pin de transacción")) {
            campoPinTransaccion.setText("");
            campoPinTransaccion.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoPinTransaccionMouseClicked

    private void campoPinTransaccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPinTransaccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPinTransaccionActionPerformed

    private void campoCuentaDepositarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoCuentaDepositarMouseClicked
        // Al hacer click en ingresar número de cuenta se borra el string por defecto
        if (campoCuentaDestinatario.getText().equals("Ingrese el número de cuenta")) {
            campoCuentaDestinatario.setText("");
            campoCuentaDestinatario.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoCuentaDepositarMouseClicked

    private void campoCuentaDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCuentaDepositarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoCuentaDepositarActionPerformed

    private void campoMontoDepositoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoMontoDepositoMouseClicked
        // Al hacer click en ingresar monto a depositar se borra el string por defecto
        if (campoMonto.getText().equals("Ingrese el monto a depositar")){
            campoMonto.setText("");
            campoMonto.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoMontoDepositoMouseClicked

    private void campoMontoDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoMontoDepositoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoMontoDepositoActionPerformed

    private void campoPinTransaccion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPinTransaccion1MouseClicked
        //Al hacer click en ingresar pin de transacción se borra el string por defecto
        if (campoPinTransaccion.getText().equals("Ingrese su pin de transacción")) {
            campoPinTransaccion.setText("");
            campoPinTransaccion.setForeground(Color.black);
        }
    }//GEN-LAST:event_campoPinTransaccion1MouseClicked

    private void campoPinTransaccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPinTransaccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPinTransaccion1ActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
		// Al clickear el botón volver  te lleva nuevamente a la ventana pantallaPrincipal
		pantallaPrincipal newFrame = new pantallaPrincipal();
		newFrame.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void campoCuentaDepositarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCuentaDepositarKeyTyped
		int key = evt.getKeyChar();

		boolean numeros = key >= 48 && key <= 57;

		if (!numeros) {
			evt.consume();
		}
    }//GEN-LAST:event_campoCuentaDepositarKeyTyped

    private void campoMontoDepositoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoMontoDepositoKeyTyped
		int key = evt.getKeyChar();

		boolean numeros = key >= 48 && key <= 57;

		if (!numeros) {
			evt.consume();
		}
    }//GEN-LAST:event_campoMontoDepositoKeyTyped

    private void campoPinTransaccion1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPinTransaccion1KeyTyped
		int key = evt.getKeyChar();

		boolean numeros = key >= 48 && key <= 57;

		if (!numeros) {
			evt.consume();
		}
    }//GEN-LAST:event_campoPinTransaccion1KeyTyped

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(depositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(depositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(depositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(depositar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new depositar().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoDestinatarioLabel;
    private javax.swing.JButton botonDepositar;
    private javax.swing.JButton botonVolver;
    private javax.swing.JTextField campoApellidoDestinatario;
    private javax.swing.JTextField campoCedulaDestinatario;
    private javax.swing.JTextField campoCuentaDepositar;
    private javax.swing.JTextField campoCuentaDestinatario;
    private javax.swing.JTextField campoMonto;
    private javax.swing.JTextField campoMontoDeposito;
    private javax.swing.JTextField campoNombreDestinatario;
    private javax.swing.JTextField campoPinTransaccion;
    private javax.swing.JTextField campoPinTransaccion1;
    private javax.swing.JLabel cedulaDestinatarioLabel;
    private javax.swing.JLabel cuentaDepositarLabel;
    private javax.swing.JLabel cuentaDestinatarioLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel logoTaoDepositar;
    private javax.swing.JLabel montoDepositoLabel;
    private javax.swing.JLabel montoLabel;
    private javax.swing.JLabel nombreDestinatarioLabel;
    private javax.swing.JLabel pinTransaccionLabel;
    private javax.swing.JLabel pinTransaccionLabel1;
    // End of variables declaration//GEN-END:variables
}
