
package com.taobanking.ui.interfaz;

import java.awt.Color;

/**
 *
 * @author HP
 */
public class nuevaCuenta extends javax.swing.JFrame {

	/**
	 * Creates new form nuevaCuenta
	 */
	public nuevaCuenta() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoTaoNuevaCuenta = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cedulaLabel = new javax.swing.JLabel();
        pinCuentaLabel = new javax.swing.JLabel();
        campoPinCuenta = new javax.swing.JTextField();
        fechaNacLabel = new javax.swing.JLabel();
        apellidoLabel = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoApellido = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        campoCedula = new javax.swing.JTextField();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        botonCrearNuevaCuenta = new javax.swing.JButton();
        botonVolverNuevaCuenta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(620, 415));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoTaoNuevaCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoTaoBankingRecortado.png"))); // NOI18N
        jPanel1.add(logoTaoNuevaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 130, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3), "Nueva Cuenta", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 1, 14), new java.awt.Color(102, 102, 102))); // NOI18N

        cedulaLabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        cedulaLabel.setForeground(new java.awt.Color(0, 0, 0));
        cedulaLabel.setText("Nro. de Cédula");

        pinCuentaLabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        pinCuentaLabel.setForeground(new java.awt.Color(0, 0, 0));
        pinCuentaLabel.setText("Pin de Cuenta");

        campoPinCuenta.setBackground(new java.awt.Color(255, 255, 255));
        campoPinCuenta.setForeground(new java.awt.Color(153, 153, 153));
        campoPinCuenta.setText("Ingrese su pin de cuenta");
        campoPinCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoPinCuentaMouseClicked(evt);
            }
        });
        campoPinCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPinCuentaActionPerformed(evt);
            }
        });
        campoPinCuenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoPinCuentaKeyTyped(evt);
            }
        });

        fechaNacLabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        fechaNacLabel.setForeground(new java.awt.Color(0, 0, 0));
        fechaNacLabel.setText("Fecha de Nacimiento");

        apellidoLabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        apellidoLabel.setForeground(new java.awt.Color(0, 0, 0));
        apellidoLabel.setText("Apellido");

        campoNombre.setBackground(new java.awt.Color(255, 255, 255));
        campoNombre.setForeground(new java.awt.Color(153, 153, 153));
        campoNombre.setText("Ingrese su nombre");
        campoNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoNombreMouseClicked(evt);
            }
        });
        campoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoNombreActionPerformed(evt);
            }
        });
        campoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoNombreKeyTyped(evt);
            }
        });

        campoApellido.setBackground(new java.awt.Color(255, 255, 255));
        campoApellido.setForeground(new java.awt.Color(153, 153, 153));
        campoApellido.setText("Ingrese su apellido");
        campoApellido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoApellidoMouseClicked(evt);
            }
        });
        campoApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoApellidoActionPerformed(evt);
            }
        });
        campoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoApellidoKeyTyped(evt);
            }
        });

        nombreLabel.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(0, 0, 0));
        nombreLabel.setText("Nombre");

        campoCedula.setBackground(new java.awt.Color(255, 255, 255));
        campoCedula.setForeground(new java.awt.Color(153, 153, 153));
        campoCedula.setText("Ingrese su número de cédula");
        campoCedula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                campoCedulaMouseClicked(evt);
            }
        });
        campoCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoCedulaActionPerformed(evt);
            }
        });
        campoCedula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                campoCedulaKeyTyped(evt);
            }
        });

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(apellidoLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fechaNacLabel, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(campoPinCuenta)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(pinCuentaLabel)
                        .addComponent(cedulaLabel))
                    .addComponent(campoCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLabel)
                    .addComponent(cedulaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(campoCedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoLabel)
                    .addComponent(pinCuentaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoPinCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(fechaNacLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        botonCrearNuevaCuenta.setText("CREAR");
        botonCrearNuevaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearNuevaCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(botonCrearNuevaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        botonVolverNuevaCuenta.setText("VOLVER");
        botonVolverNuevaCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverNuevaCuentaActionPerformed(evt);
            }
        });
        jPanel1.add(botonVolverNuevaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 120, 70));

        jPanel4.setBackground(new java.awt.Color(242, 69, 69));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 170, 70));

        jPanel5.setBackground(new java.awt.Color(201, 42, 42));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoApellidoActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_campoApellidoActionPerformed

    private void campoCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoCedulaActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_campoCedulaActionPerformed

    private void campoPinCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPinCuentaActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_campoPinCuentaActionPerformed

    private void campoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoNombreActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_campoNombreActionPerformed

    private void campoNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoNombreMouseClicked
		// Al hacer click en ingresar nombre se borra el string por defecto
		if (campoNombre.getText().equals("Ingrese su nombre")) {
			campoNombre.setText("");
			campoNombre.setForeground(Color.black);
		}
    }//GEN-LAST:event_campoNombreMouseClicked

    private void campoApellidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoApellidoMouseClicked
		// Al hacer click en ingresar apellido se borra el string por defecto
		if (campoApellido.getText().equals("Ingrese su apellido")) {
			campoApellido.setText("");
			campoApellido.setForeground(Color.black);
		}
    }//GEN-LAST:event_campoApellidoMouseClicked

    private void campoCedulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoCedulaMouseClicked
		// Al hacer click en ingresar numero de cuenta se borra el string por defecto
		if (campoCedula.getText().equals("Ingrese su número de cédula")) {
			campoCedula.setText("");
			campoCedula.setForeground(Color.black);
		}
    }//GEN-LAST:event_campoCedulaMouseClicked

    private void campoPinCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_campoPinCuentaMouseClicked
		// Al hacer click en ingresar pin de cuenta se borra el string por defecto
		if (campoPinCuenta.getText().equals("Ingrese su pin de cuenta")) {
			campoPinCuenta.setText("");
			campoPinCuenta.setForeground(Color.black);
		}
    }//GEN-LAST:event_campoPinCuentaMouseClicked

    private void botonVolverNuevaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverNuevaCuentaActionPerformed
		// Al hacer click a este botón te lleva a la ventana principal de acceso
		acceso newFrame = new acceso();
		newFrame.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_botonVolverNuevaCuentaActionPerformed

    private void botonCrearNuevaCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearNuevaCuentaActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_botonCrearNuevaCuentaActionPerformed

    private void campoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoNombreKeyTyped

    }//GEN-LAST:event_campoNombreKeyTyped

    private void campoApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoApellidoKeyTyped

    }//GEN-LAST:event_campoApellidoKeyTyped

    private void campoCedulaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoCedulaKeyTyped

    }//GEN-LAST:event_campoCedulaKeyTyped

    private void campoPinCuentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoPinCuentaKeyTyped
		int key = evt.getKeyChar();

		boolean numeros = key >= 48 && key <= 57;

		if (!numeros) {
			evt.consume();
		}
    }//GEN-LAST:event_campoPinCuentaKeyTyped

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(nuevaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(nuevaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(nuevaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(nuevaCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new nuevaCuenta().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidoLabel;
    private javax.swing.JButton botonCrearNuevaCuenta;
    private javax.swing.JButton botonVolverNuevaCuenta;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoCedula;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JTextField campoPinCuenta;
    private javax.swing.JLabel cedulaLabel;
    private javax.swing.JLabel fechaNacLabel;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logoTaoNuevaCuenta;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel pinCuentaLabel;
    // End of variables declaration//GEN-END:variables
}
