/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.taobanking.ui.interfaz;
/**
 *
 * @author HP
 */
public class pantallaPrincipal extends javax.swing.JFrame {

	/**
	 * Creates new form pantallaPrincipal
	 */
	public pantallaPrincipal() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT
	 * modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logoTaoPantallaPrincipal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        iconoInvitadoPantallaPrincipal = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JLabel();
        apellidoUsuario = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        botonCerrarSesion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        botonSaldoPantallaPrincipal = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        botonTransferencia = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        botonServicios = new javax.swing.JLabel();
        botonPagoTarjeta = new javax.swing.JLabel();
        botonDepositar = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(620, 415));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 385));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoTaoPantallaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoTaoBankingRecortado.png"))); // NOI18N
        jPanel1.add(logoTaoPantallaPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 130, 70));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 0, 150, 66));

        jPanel3.setBackground(new java.awt.Color(242, 69, 69));
        jPanel3.setPreferredSize(new java.awt.Dimension(135, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 140, 66));

        jPanel4.setBackground(new java.awt.Color(201, 42, 42));

        iconoInvitadoPantallaPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconoInvitadoPantallaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-usuario-de-género-neutro-64.png"))); // NOI18N

        nombreUsuario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        nombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        nombreUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreUsuario.setText("Horny");

        apellidoUsuario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        apellidoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        apellidoUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        apellidoUsuario.setText("Saldivar");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iconoInvitadoPantallaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
            .addComponent(nombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(apellidoUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addComponent(iconoInvitadoPantallaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellidoUsuario)
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 200));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        botonCerrarSesion.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        botonCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoCerrarSesion.png"))); // NOI18N
        botonCerrarSesion.setText("Cerrar Sesión");
        botonCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCerrarSesionMouseClicked(evt);
            }
        });

        botonSaldoPantallaPrincipal.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        botonSaldoPantallaPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        botonSaldoPantallaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoSaldo.png"))); // NOI18N
        botonSaldoPantallaPrincipal.setText("Consultar Saldo");
        botonSaldoPantallaPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(botonSaldoPantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(botonSaldoPantallaPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 180, 230));

        botonTransferencia.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        botonTransferencia.setForeground(new java.awt.Color(0, 0, 0));
        botonTransferencia.setText("TRANSFERENCIA");
        botonTransferencia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonTransferencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonTransferenciaMouseClicked(evt);
            }
        });
        jPanel1.add(botonTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 260, -1));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 260, 10));

        botonServicios.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        botonServicios.setForeground(new java.awt.Color(0, 0, 0));
        botonServicios.setText("PAGO DE SERVICIOS");
        botonServicios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(botonServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 260, -1));

        botonPagoTarjeta.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        botonPagoTarjeta.setForeground(new java.awt.Color(0, 0, 0));
        botonPagoTarjeta.setText("PAGO DE TARJETA");
        botonPagoTarjeta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(botonPagoTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 260, -1));

        botonDepositar.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        botonDepositar.setForeground(new java.awt.Color(0, 0, 0));
        botonDepositar.setText("DEPOSITAR");
        botonDepositar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonDepositar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonDepositarMouseClicked(evt);
            }
        });
        jPanel1.add(botonDepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 260, -1));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 260, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 260, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 260, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarSesionMouseClicked
	// Función que te retorna al frame de acceso al clickear cerrar sesión en la pantallaPrincipal
	acceso nf = new acceso();
	nf.setVisible(true);
	this.dispose();
    }//GEN-LAST:event_botonCerrarSesionMouseClicked

    private void botonDepositarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonDepositarMouseClicked
		// Al clickear depositar te lleva a la ventana depositar
		depositar newFrame = new depositar();
		newFrame.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_botonDepositarMouseClicked

    private void botonTransferenciaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonTransferenciaMouseClicked
		// Al clickear transferencias te lleva a la ventana transferencias
		transferencias newFrame = new transferencias();
		newFrame.setVisible(true);
		this.dispose();
    }//GEN-LAST:event_botonTransferenciaMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new pantallaPrincipal().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel apellidoUsuario;
    private javax.swing.JLabel botonCerrarSesion;
    private javax.swing.JLabel botonDepositar;
    private javax.swing.JLabel botonPagoTarjeta;
    private javax.swing.JLabel botonSaldoPantallaPrincipal;
    private javax.swing.JLabel botonServicios;
    private javax.swing.JLabel botonTransferencia;
    private javax.swing.JLabel iconoInvitadoPantallaPrincipal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel logoTaoPantallaPrincipal;
    public javax.swing.JLabel nombreUsuario;
    // End of variables declaration//GEN-END:variables
}
